### ISSUE TITLE
Ensure swap is disable on all nodes

### ISSUE THREAD

**Issue by oswalya** [anmoel/ansible-role-kubernetes#20]
Swap should be disabled when running kubernetes. 
The play should check if swap is enabled and disable it if necessary.

Otherwise using your role might result in:

F1129 19:04:46.741210    8662 server.go:262] failed to run Kubelet: Running with swap on is not supported, please disable swap! or set --fail-swap-on flag to false.

**Comment by anmoel** [comment]
issue is fixed
